### PR TITLE
Make Free Generator also empty cuda cache

### PR DESCRIPTION
**Pull request by NullSenseStudio**
I never noticed any VRAM releasing when activating Free Generator before making these changes.

`torch.cuda.empty_cache()` doesn't quite clear everything on its own and `generator.model.cpu()` seems to let it clear some more. Still had about 750MB of VRAM uncleared (according to `torch.cuda.memory_reserved()`) after that. I can't figure out how to clear the rest.

Unsure if `torch.cuda.empty_cache()` may error for a non-cuda system, someone else with appropriate hardware will have to test.

Not a perfect solution for #42, but it does seem to mostly do what it needs now.

### CODE REVIEW

**Comment by carson-katri** [comment]
Thanks for investigating this! I develop primarily on Mac, so it was tricky to figure this out because the memory is unified.

I’ll try to find a suitable solution for Apple Silicon to include in this before merging.

**Comment by NullSenseStudio** [comment]
Also just thought it may be useful to run this automatically on `bpy.app.handlers.render_init` for people who don't realize the operator exists or just forgot to run it.

**Comment by carson-katri** [comment]
This doesn't crash on Apple Silicon, but it has no effect. I was not able to find any similar function for MPS unfortunately.

**Comment by NullSenseStudio** [comment]
Could move the generator to its own process and just kill it. Would also allow for easily cancelling in the middle of generating in case someone had their settings too high. Also may save blender from crashing in a few cases when the generator runs into issues.

**Pull request closed without merging**
