### PR TITLE
Add preload models step

### PR DESCRIPTION
**Pull request by carson-katri**
This is run every time the `GeneratorProcess` is started, so you don't need to do more than one thing in the preferences window. I also did not use the `preload_models.py` script from InvokeAI for more control over how it works.

### CODE REVIEW

**Comment by carson-katri** [comment]
The progress is now shown for each model download:

Screen Shot 2022-09-26 at 7 09 08 PM

**Comment by carson-katri** [comment]
@NullSenseStudio @blastframe 
There was a bug in this PR, but this one seems to be ok: https://github.com/carson-katri/dream-textures/actions/runs/3132180840
Can someone else give this a try before I release?

**Comment by blastframe** [comment]
@carson-katri I'm happy to help if I can. Downloading now.

**Comment by carson-katri** [comment]
@blastframe Thanks! if you can, delete the huggingface caches in `%HOMEPATH%\.cache` before generating your first image.

**Comment by NullSenseStudio** [comment]
I can test too, but won't be until tomorrow if you're okay with waiting.

**Comment by NullSenseStudio** [comment]
Worked perfectly for me. Also deleted torch within `.cache` to make sure the `checkpoint_liberty_with_aug.pth` file there would download too.

**Comment by NullSenseStudio** [comment]
Is there any reason why the artifact is nested within a second .zip?

**Comment by carson-katri** [comment]
The upload-artifact action creates a zip even if you pass it a zip to upload. And I need to compress it first or it compresses the directory bizarrely. I think it was trying to compress each file in the directory as its own artifact when I didn’t compress it first.

**Pull request merged**
